#ifndef INPUT_IMAGE_XCEPTION_H
#define INPUT_IMAGE_XCEPTION_H

#include "xception_params.h"

// Input Image Data (Preprocessed for Xception, e.g., from dog.jpg)
// Format: 3x299x299 (C, H, W), Flattened
// Values should be preprocessed (e.g., scaled to [-1, 1])
static const float input_image_data[INPUT_H * INPUT_W * INPUT_C] = {
    // 268203 float values generated by script...
    0.12345678f, -0.98765432f, 0.55555555f, /* ... */ 0.11111111f,
    // ... many ... many ... lines ...
   -0.88888888f, 0.0f, 0.9999999f
};

#endif // INPUT_IMAGE_XCEPTION_H